language: rust
rust:
  - nightly
  - stable
  - beta
  - 1.9.0

os:
  - linux
  - osx

matrix:
    allow_failures:
        - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include; fi

script:
  - cargo test
  - cargo doc --no-deps
