[package]
name = "tldextract"
version = "0.1.0"
authors = ["Mohammed Makhlouf <msmakhlouf@gmail.com>", "Mohamad Samir <msamirdev92@gmail.com>"]
[dependencies]
hyper = "0.7.2"
regex = "0.1"
idna = "0.1.0"
log = "0.3.6"
fern = "0.3.5"
